In [2]:
#几个重要的工具
import numpy as np #科学计算的基础
import scipy #科学计算的工具 但一般用numpy
import pandas as pd # 大杀器，借用R里的data frame的数据结构，
import sklearn #非常方便，基本集成了所有机器学习的包
import keras.backend as K #深度学习的工具
import tensorflow as tf #深度学习的工具 环境应为 python 3.5
#安装tensorflow --> 在Anaconda Promp 里打入
#> conda create -n python35 python=3.5
#> activate python35
#> pip install tensorflow

ModuleNotFoundError: No module named 'keras'

In [ ]:
#numpy 定义了python进行矩阵数值计算的基础
np.add(A,B)
np.substract(A,B)
np.dot(C,D) #矩阵乘法 
np.matmul(C,D)##C@D 矩阵乘法
# dot 
np.multiply(C,D)##C*D 矩阵相同位置上元素相乘

In [11]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B =',np.add(A,B))
print('A-B =',np.subtract(A,B))
print(A@B)
print(A*B)

A+B = [5 5 3]
A-B = [-3 -1  3]
10
[4 6 0]


In [3]:
C = np.array([[1,2,3],
            [1,1,1]])
D = np.array([[4,3,9,9],
            [1,1,2,2],
            [4,2,1,1]])
#矩阵乘法
print('n[.dot(C,D) = ]',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))# matmul= matrix multiplication
print('C@D = ',C@D)

#对应位置上的元素与元素相乘 hadamard product, 哈达马积乘积
print('np.multiply(D,D)=',np.multiply(D,D))
print('D*D =',D*D)

n[.dot(C,D) = ] [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
C@D =  [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D)= [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
D*D = [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


In [7]:
C.shape

(2, 3)

In [8]:
D.shape

(3, 4)

In [ ]:
from sklearn import datasets
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso